In [1]:
import numpy as np

In [2]:
list1 = [10, 20 ,30]
list1

[10, 20, 30]

In [3]:
arr1 = np.array(list1)
arr1

array([10, 20, 30])

In [4]:
type(arr1)

numpy.ndarray

nd = n-dimensional

In [5]:
arr2 = np.arrange(10, 20, 1)
arr2

AttributeError: module 'numpy' has no attribute 'arrange'

In [6]:
arr2 = np.arange(10, 20, 1)
arr2

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19])

In [7]:
list1

[10, 20, 30]

In [8]:
list2 = [40, 50, 60]

In [9]:
list3 = [list1, list2]
list3

[[10, 20, 30], [40, 50, 60]]

In [10]:
arr3 = np.array(list3)
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [11]:
arr3.shape

(2, 3)

## Matrix Operations

In [12]:
list1 * 3

[10, 20, 30, 10, 20, 30, 10, 20, 30]

In [13]:
arr11 = np.array(list2)
arr11

array([40, 50, 60])

In [14]:
arr1.shape == arr11.shape

True

In [15]:
arr1 * arr11

array([ 400, 1000, 1800])

## Task

Create ndarrays of the following sizes:
1. One dimensional array with 12 elements (12,)
2. Two dimensional array of size (3, 4)
3. Three dimensional array of size (2, 5, 4)

In [16]:
a1 = np.arange(1, 13)

In [17]:
a1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12])

In [20]:
a2 = np.array([[1,2,3,4], [5,6,7,8], [9,10,11,12]])
a2.shape

(3, 4)

In [27]:
a3 = np.array(
    [
        [[1,2,3,4], [1,2,3,4], [1,2,3,4], [1,2,3,4], [1,2,3,4]],
        [[1,2,3,4], [1,2,3,4], [1,2,3,4], [1,2,3,4], [1,2,3,4]]
    ]
)
a3.shape

(2, 5, 4)

In [28]:
np.zeros((12))

array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

In [29]:
np.zeros((3, 4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [33]:
np.zeros((2,5,4), dtype=int)

array([[[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]],

       [[0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0],
        [0, 0, 0, 0]]])

In [34]:
arr1

array([10, 20, 30])

In [31]:
arr3

array([[10, 20, 30],
       [40, 50, 60]])

In [35]:
arr1[1]

20

In [36]:
arr3[1]

array([40, 50, 60])

In [37]:
arr3[1][2]

60

In [38]:
arr3[1,2]

60

In [39]:
arr3[0]

array([10, 20, 30])

In [40]:
arr3[:,1]

array([20, 50])

In [41]:
a3[:,:,1]

array([[2, 2, 2, 2, 2],
       [2, 2, 2, 2, 2]])

In [43]:
a3.sum()

100

In [44]:
a3.mean()

2.5

In [45]:
a3.std()

1.118033988749895

# a3.mean(INSERT COLUMN)

In [46]:
a3.min()

1

In [47]:
a3.max()

4

In [48]:
for x in arr1:
    print(x)

10
20
30


In [49]:
for dim in a3:
    for x in dim:
        print(x)

[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]
[1 2 3 4]


In [50]:
for x in np.nditer(a3):
    print(x)

1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4
1
2
3
4


In [51]:
np.save("3d_array", a3)

In [52]:
np.load("3d_array.npy")

array([[[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]],

       [[1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4],
        [1, 2, 3, 4]]])

In [57]:
np.savetxt("3d_array.txt", a3, delimiter='\t')

ValueError: Expected 1D or 2D array, got 3D array instead